### ISSUE TITLE
[Bug] GitHub Actions build task succeeds even when compilation fails

### ISSUE THREAD

**Issue by andrebrait** [qmk/qmk_userspace#5]
### Describe the Bug

When running the GitHub Actions build flow, it succeeds even if it fails to compile and/or produce any artifacts. 
I'm not sure whether that was intended.

### Additional Context?

Example run: https://github.com/andrebrait/qmk_userspace/actions/runs/7771624531

**Comment by andrebrait** [comment]
I guess this actually belongs in https://github.com/qmk/.github, correct?

**Comment by tzarc** [comment]
> I guess this actually belongs in [qmk/.github](https://github.com/qmk/.github), correct?

Eh, close enough here. Probably better visibility. Will have a look -- mine's failing too so at least I have a local repro.

**Comment by tzarc** [comment]
Fixed.
